# WSL
# [terminal]
# [terminal.shell]
# program = "wsl.exe"
# args = ["--cd", "~"]

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"
padding = { x = 0, y = 0 }
option_as_alt = "Both"
opacity = 1

[env]
TERM = "xterm-256color"
